name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clang
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install clang \
          libc6-devel
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make triple-test
      run: make triple-test
